FROM tomcat:8.0
ADD ‘http://35.229.126.2:8080/job/pelda1/lastBuild/com.devops$SampleWebApplication/artifact/com.devops/SampleWebApplication/1.0-SNAPSHOT/SampleWebApplication-1.0-SNAPSHOT.war’ /usr/local/tomcat/webapps/

